name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Read version
      id: read_version
      run: echo "::set-output name=version::$(cat src/plastic_balanced_network/VERSION)"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

    - name: Run flake8
      run: flake8 --config=.flake8 src/plastic_balanced_network

    - name: Run black
      run: black --check src/plastic_balanced_network
      env:
        PYTHONPATH: ${{ env.PYTHONPATH }}:${{ github.workspace }}
      working-directory: .

    - name: Generate documentation
      run: |
        pip install sphinx sphinx-rtd-theme
        sphinx-quickstart -p plastic_balanced_network -a "Alan Akil" -q --ext-autodoc --ext-viewcode --ext-intersphinx --ext-todo docs
        sphinx-build -b html docs docs/_build

    - name: Publish documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./docs/_build/html

