name: Publish to PyPI.org

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11, 3.12]
      fail-fast: false  # Let's keep building even if one fails
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install build
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      # Save the dist/ artifacts (the wheels & sdist) with a name
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.python-version }}
          path: dist/*
  
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts for all Pythons
        uses: actions/download-artifact@v3
        with:
          # Pick up all artifacts whose name starts with 'dist-'
          name: dist-*
          path: dist

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
